import { useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { ArrowLeft, ArrowUpRight, CalendarDays, LockKeyhole, X } from 'lucide-react'
import { editorHtml } from '../../lib/letterUtils'

export type LetterEditorProps = { title: string; body: string; date: string; setTitle: (value: string) => void; setBody: (value: string) => void; setDate: (value: string) => void; onSave: (status: 'draft' | 'published') => void; onCancel: () => void; published: boolean; other: string }

export default function LetterEditor({ title, body, date, setTitle, setBody, setDate, onSave, onCancel, published, other }: LetterEditorProps) {
  const editorRef = useRef<HTMLDivElement>(null)
  useEffect(() => { const value = editorHtml(body); if (editorRef.current && editorRef.current.innerHTML !== value) editorRef.current.innerHTML = value }, [body])
  const apply = (command: string) => { const area = editorRef.current; if (!area) return; area.focus(); document.execCommand(command); setBody(area.innerHTML) }

  return <motion.section className="editor-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
    <div className="editor-head"><button className="back-button" onClick={onCancel}><ArrowLeft size={15}/> voltar</button><span>UMA CARTA PARTICULAR</span></div>
    {published ? <div className="delivered"><motion.div initial={{ scale: .75, rotate: -10 }} animate={{ scale: 1, rotate: 0 }} transition={{ type: 'spring' }}><span>✉</span></motion.div><h2>Carta entregue.</h2><p>Suas palavras já estão a caminho.</p></div> : <><div className="letter-to">Para <span>{other}</span><span className="to-line"/></div><input className="title-input" placeholder="Dê um nome para essa carta..." value={title} onChange={event => setTitle(event.target.value)} maxLength={120}/><div className="toolbar"><button title="Negrito" onMouseDown={event => event.preventDefault()} onClick={() => apply('bold')}><b>B</b></button><button title="Itálico" onMouseDown={event => event.preventDefault()} onClick={() => apply('italic')}><i>I</i></button><i/><button title="Lista" onMouseDown={event => event.preventDefault()} onClick={() => apply('insertUnorderedList')}>☷</button><button title="Alinhar ao centro" onMouseDown={event => event.preventDefault()} onClick={() => apply('justifyCenter')}>≡</button><button title="Alinhar à esquerda" onMouseDown={event => event.preventDefault()} onClick={() => apply('justifyLeft')}>☰</button><span>palavras guardadas com cuidado</span></div><div ref={editorRef} className="letter-editor" contentEditable role="textbox" aria-label="Texto da carta" aria-multiline="true" data-placeholder="Escreva o que você gostaria de dizer..." suppressContentEditableWarning onInput={event => setBody(event.currentTarget.innerHTML)}/><div className="future-option"><div className="future-label"><CalendarDays size={16}/><span><b>Uma carta para o futuro</b><small>Escolha quando ela poderá ser aberta</small></span></div><input type="date" min={new Date(Date.now() + 86400000).toISOString().slice(0,10)} value={date} onChange={event => setDate(event.target.value)} aria-label="Data para abrir a carta"/>{date && <button className="clear-date" onClick={() => setDate('')} aria-label="Remover data"><X size={14}/></button>}</div><div className="editor-actions"><button className="draft-button" onClick={() => onSave('draft')}>Salvar rascunho</button><button className="publish-button" disabled={!title.trim() || !body.trim()} onClick={() => onSave('published')}>Publicar carta <ArrowUpRight size={15}/></button></div><p className="editor-foot"><LockKeyhole size={12}/> só você pode ver este texto até a publicação</p></>}
  </motion.section>
}
